### PR TITLE
Prevent occasional stuttering on the scrolling of the middle layer.

### PR DESCRIPTION
**Pull request by vanfanel**
All the layers where scrolling fine (totally smooth), except the middle one, which showed occasional stuttering/juddering due to the fact that it was using an uneven position increase value (namely 3) while there is an even number of possible positions.

### CODE REVIEW

**Comment by segrax** [comment]
Thanks @vanfanel,

Although this does introduce a problem, the two background images now move together as though they are one image,

Whereas in the original, they are separate, giving the illusion of the clouds and the mountains moving at different speeds

[Amiga Version](https://youtu.be/1XUqK4l3VAU?t=289)

image

**Comment by vanfanel** [comment]
@segrax I have taken care of that in https://github.com/OpenFodder/openfodder/pull/79/commits/239716cb2d34b97ef3157777bd6f1fd26fdfa8f4

I think it's perfect now, what do you think?

**Comment by segrax** [comment]
I don't know if its of any help, but the code here is closer to the PC version than the Amiga version,

The Amiga looks like this,

```
void sub_A7A5C() {
    *dword_826C8 = 0x8000;

    if (*word_826B0 == 0x0C) {
        goto loc_A7A88;
    }

    *word_826B0 -= 4;

    if (*word_826B0 > 0x0C) {
        goto loc_A7A88;
    }

    *word_826B0 = 0x0C;

loc_A7A88:
    uint16_t d0 = 0x158;
    d0 -= *word_826B0;
    *word_826C4 = d0;

    uint32_t temp = *dword_826C8;
    *dword_826B4 -= temp;

    if ((int32_t)(*dword_826B4) < 0) {
        *dword_826B4 += 0x140;
    }

    d0 <<= 1;
    *dword_826B8 -= d0;

    if ((int32_t)(*dword_826B8) < 0) {
        *dword_826B8 += 0x140;
    }

    d0 <<= 1;
    *dword_826BC -= d0;

    if ((int32_t)(*dword_826BC) < 0) {
        *dword_826BC += 0x140;
    }

    d0 <<= 1;
    *dword_826C0 -= d0;

    if ((int32_t)(*dword_826C0) < 0) {
        *dword_826C0 += 0x140;
    }
}
```

it also does this with the result, and i'm not sure what happens to the outputs here. I've never investigated any further
```
void sub_A7C66() {
    uint16_t d0, d1, d2;


    d0 = *word_826B0 & 0x000F;
    d0 ^= 0x000F;
    *dword_3250 = d0;


    d0 = *dword_826B4 & 0x000F;
    d0 ^= 0x000F;
    *word_3292 = d0;


    d0 = *dword_826B8 & 0x000F;
    d0 ^= 0x000F;
    d0 <<= 4;
    *word_3292 |= d0;
    d1 = d0;


    d0 = *dword_826BC & 0x000F;
    d0 ^= 0x000F;
    d2 = d0;
    d0 |= d1;
    *word_32D2 = d0;


    d0 = *dword_826C0 & 0x000F;
    d0 ^= 0x000F;
    d0 <<= 4;
    d0 |= d2;
    *word_3316 = d0;


    d0 = *word_826C4 & 0x000F;
    d0 ^= 0x000F;
    *word_335A = d0;
}
```

**Comment by segrax** [comment]
@vanfanel yeah, that looks good to me!

**Comment by segrax** [comment]
Thanks!

**Pull request merged**
