### PR TITLE
Implements a basic CMake build system.

### PR DESCRIPTION
**Pull request by Richmondez**
Expects to be out of the source tree, so build process is something like the following:

git clone https://github.com/OpenFodder/openfodder.git
cd openfodder
mkdir build
cd build
cmake ..
make
cp openfodder ../Run

For windows you will need to add -DSDL2_ROOT_DIR=C:\PATH\TO\SDL2 -DSDL2MIXER_ROOT_DIR=C:\PATH\TO\SDL2MIXER so it knows where to look for SDL2 components though it can find MSYS2 installed mingw-w64 version of SDL2 without them.

### CODE REVIEW

**Comment by segrax** [comment]
Hi @Richmondez 

Thanks for taking the time to put this together, 

I'll give it a try one night this week!

**Comment by xcom169** [comment]
I will also try this on Manjaro, because normal makefile, AUR is not working anymore.

**Comment by poeschel** [comment]
Tested this on recent debian testing. Works like a charm. Please merge.

**Comment by segrax** [comment]
Merged!
Apologies for the extremely slow response

**Pull request merged**
